/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.discordbot;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import sx.blah.discord.api.IDiscordClient;
import sx.blah.discord.handle.obj.IChannel;
import sx.blah.discord.handle.obj.IGuild;

/**
 *
 * @author Evyatar M
 */
public class botFrame extends javax.swing.JFrame {

    private static IDiscordClient client;
 // private static Map<String, Map<String, java.awt.TextArea>> guilds;
    private static Map<String, java.awt.TextArea> channels;
    private static String[][] guildsArray;
    private static javax.swing.JTabbedPane[] channelsByGuild;
    private static Logger frameLogger = Logger.getLogger("Frame Logger");

    /**
     * Creates new form botFrame
     */
    public botFrame(IDiscordClient client) {
        this.client = client;
        initComponents();
        this.guildsPane.removeAll();

    }

    public void initiateTabs() {
        frameLogger.log(Level.WARNING, "Initializing Frame tabs");
        System.out.println("lala");
        guildsArray = new String[client.getGuilds().size()][];
        channelsByGuild = new javax.swing.JTabbedPane[client.getGuilds().size()];
        int i = 0;
        channels = new HashMap<String, java.awt.TextArea>();
        for (IGuild guild : client.getGuilds()) {
            guildsArray[i] = new String[guild.getChannels().size()];
            javax.swing.JTabbedPane newGuildTab = new javax.swing.JTabbedPane();
            guildsPane.add(guild.getName(), newGuildTab);
            channelsByGuild[i] = newGuildTab;
            int j = 0;
            for (IChannel ch : guild.getChannels()) {
                guildsArray[i][j] = ch.getID();
                java.awt.TextArea channelTextArea = new java.awt.TextArea();
                channels.put(ch.getID(), channelTextArea);
                newGuildTab.add(ch.getName(), channelTextArea);
                j++;
            }
            i++;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMessageTextField = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        guildsPane = new javax.swing.JTabbedPane();
        channelsPane = new javax.swing.JTabbedPane();
        textArea1 = new java.awt.TextArea();
        sendButton = new javax.swing.JButton();
        tabInitiationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        newMessageTextField.setToolTipText("");
        newMessageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMessageTextFieldActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        channelsPane.addTab("tab1", textArea1);

        guildsPane.addTab("tab1", channelsPane);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        tabInitiationButton.setText("Initiate");
        tabInitiationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabInitiationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guildsPane)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(logoutButton)
                        .addGap(40, 40, 40)
                        .addComponent(loginButton)
                        .addGap(40, 40, 40)
                        .addComponent(tabInitiationButton)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newMessageTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(loginButton)
                    .addComponent(tabInitiationButton))
                .addGap(10, 10, 10)
                .addComponent(guildsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            if (client.isReady()) {
                client.logout();
            }
        } catch (Exception exc) {
            frameLogger.log(Level.WARNING, "Exception - Logout button " + exc);
        }

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        try {

            if (!client.isReady()) {
                client = Dbot.login();

            }
        } catch (Exception exc) {
            frameLogger.log(Level.WARNING, "Exception - Login button " + exc);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void tabInitiationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabInitiationButtonActionPerformed
        initiateTabs();
        frameLogger.setLevel(Level.ALL);
        tabInitiationButton.setEnabled(false);
    }//GEN-LAST:event_tabInitiationButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            int indexOfSelectedGuild = guildsPane.getSelectedIndex();
            int indexOfSelectedCh = channelsByGuild[indexOfSelectedGuild].getSelectedIndex();
            String message = this.newMessageTextField.getText();
            String tempChID = guildsArray[indexOfSelectedGuild][indexOfSelectedCh];
            client.getChannelByID(tempChID).sendMessage(message);
            channels.get(tempChID).append(client.getOurUser().getDisplayName(client.getChannelByID(tempChID).getGuild()) + ": " + message + "\n");
            newMessageTextField.setText("");
        } catch (Exception exc) {
            frameLogger.log(Level.WARNING, "Init");
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void newMessageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMessageTextFieldActionPerformed
        this.sendButtonActionPerformed(evt);
    }//GEN-LAST:event_newMessageTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addMessages(String channelID, String message) {
        channels.get(channelID).append(message + "\n");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane channelsPane;
    private javax.swing.JTabbedPane guildsPane;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField newMessageTextField;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton tabInitiationButton;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
