/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.discordbot;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import sx.blah.discord.api.IDiscordClient;
import sx.blah.discord.handle.obj.IChannel;
import sx.blah.discord.handle.obj.IGuild;

/**
 *
 * @author Evyatar M
 */
public class botFrame extends javax.swing.JFrame {
    
    private static IDiscordClient client;
    //   private static Map<String, Map<String, java.awt.TextArea>> guilds;
    private static Map<String, java.awt.TextArea> channels;
    private static String[][] guildsArray;
    private static javax.swing.JTabbedPane[] channelsByGuild;

    /**
     * Creates new form botFrame
     */
    public botFrame(IDiscordClient client) {
        this.client = client;
        initComponents();
        this.guildsPane.removeAll();
        
    }
    
    public void initiateTabs() {
        guildsArray = new String[client.getGuilds().size()][];
        channelsByGuild = new javax.swing.JTabbedPane[client.getGuilds().size()];
        int i = 0;
        channels = new HashMap<String, java.awt.TextArea>();
        for (IGuild guild : client.getGuilds()) {
            guildsArray[i] = new String[guild.getChannels().size()];
            javax.swing.JTabbedPane newGuildTab = new javax.swing.JTabbedPane();
            guildsPane.add(guild.getName(), newGuildTab);
            channelsByGuild[i] = newGuildTab;
            int j = 0;
            for (IChannel ch : guild.getChannels()) {
                guildsArray[i][j] = ch.getID();
                java.awt.TextArea channelTextArea = new java.awt.TextArea();
                channels.put(ch.getID(), channelTextArea);
                newGuildTab.add(ch.getName(), channelTextArea);
                j++;
            }
            i++;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMessageTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        guildsPane = new javax.swing.JTabbedPane();
        channelsPane = new javax.swing.JTabbedPane();
        textArea1 = new java.awt.TextArea();
        sendButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        newMessageTextField.setToolTipText("");
        newMessageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMessageTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        channelsPane.addTab("tab1", textArea1);

        guildsPane.addTab("tab1", channelsPane);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Initiate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guildsPane)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newMessageTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(10, 10, 10)
                .addComponent(guildsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (client.isReady()) {
                client.logout();
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(rootPane, exc);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            if (!client.isReady()) {
                client = Dbot.login();
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(rootPane, exc);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        initiateTabs();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            int indexOfSelectedGuild = guildsPane.getSelectedIndex();
            int indexOfSelectedCh = channelsByGuild[indexOfSelectedGuild].getSelectedIndex();
            String message = this.newMessageTextField.getText();
            String tempChID = guildsArray[indexOfSelectedGuild][indexOfSelectedCh];
            client.getChannelByID(tempChID).sendMessage(message);
            channels.get(tempChID).append(client.getOurUser().getDisplayName(client.getChannelByID(tempChID).getGuild()) + ": " + message + "\n");
            newMessageTextField.setText("");
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(rootPane, exc);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void newMessageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMessageTextFieldActionPerformed
        this.sendButtonActionPerformed(evt);
    }//GEN-LAST:event_newMessageTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void addMessages(String channelID, String message) {
        channels.get(channelID).append(message + "\n");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane channelsPane;
    private javax.swing.JTabbedPane guildsPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField newMessageTextField;
    private javax.swing.JButton sendButton;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
